### ISSUE TITLE
"h9 publish" bails with "RequestTimeout" from Docker container

### ISSUE THREAD

**Issue by f1337** [pandastrike/haiku9#87]
`h9 serve` and `h9 build` work as expected from inside a Docker container, however `h9 publish` chokes with `RequestTimeout` errors.

There have been some related bugs closed recently by the aws-sdk maintainers (cf. https://github.com/aws/aws-sdk-js/issues/965), so upgrading to [the latest version](https://www.npmjs.com/package/aws-sdk), may help.

Or it may be caused by some networking/proxy issue. Needs investigation.

This is the only thing standing between us and making #83 a reality. I already have the changes ready in my local working copy.

```
$ docker run -it --rm --name panda-muzak -v ~/.aws:/root/.aws -v "$PWD":/usr/src/app -w /usr/src/app node npm run h9 publish staging
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
npm info lifecycle panda-music@1.0.0~preh9: panda-music@1.0.0
npm info lifecycle panda-music@1.0.0~h9: panda-music@1.0.0

> panda-music@1.0.0 h9 /usr/src/app
> h9 "publish" "staging"

Scanning S3 bucket.
Scanning local repo.
Syncing S3 bucket.
Failed to upload object. { RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
  at Request.extractError (/usr/src/app/node_modules/aws-sdk/lib/services/s3.js:334:35)
  at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
  at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:596:14)
  at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:21:10)
  at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:37:9)
  at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:598:12)
  at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:596:14)
  at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:21:10)
  at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:37:9)
  at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:598:12)
  at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  at callNextListener (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
  at IncomingMessage.onEnd (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:209:11)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:975:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  message: 'Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.',
  code: 'RequestTimeout',
  region: null,
  time: 2016-09-28T23:12:55.683Z,
  requestId: 'BF4335FCE6C352F3',
  extendedRequestId: 'RalDbDDgIflvKfgtPJjb8mpKOheeAvgnujEzgPMlmvlmeaLBt5bernZRUCtMy43GYtw/P7n7NIR95t/d9BS6RO4v/1z5Y+Gg',
  statusCode: 400,
  retryable: true }
Warning: unhandled rejection for Promise {
  <rejected> Error
  at Object.<anonymous> (/usr/src/app/node_modules/haiku9/lib/publish/bucket/sync.js:124:15)
  at undefined.throw (native)
  at /usr/src/app/node_modules/fairmont-helpers/lib/promise.js:95:34
  at step (/usr/src/app/node_modules/fairmont-helpers/lib/promise.js:81:20)
  at /usr/src/app/node_modules/fairmont-helpers/lib/promise.js:94:22
  at process._tickDomainCallback (internal/process/next_tick.js:129:7)
 }
Warning: unhandled rejection for Promise {
  <rejected> Error
  at Object.<anonymous> (/usr/src/app/node_modules/haiku9/lib/publish/bucket/sync.js:124:15)
  at undefined.throw (native)
  at /usr/src/app/node_modules/fairmont-helpers/lib/promise.js:95:34
  at step (/usr/src/app/node_modules/fairmont-helpers/lib/promise.js:81:20)
  at /usr/src/app/node_modules/fairmont-helpers/lib/promise.js:94:22
  at process._tickDomainCallback (internal/process/next_tick.js:129:7)
 }
npm info lifecycle panda-music@1.0.0~posth9: panda-music@1.0.0
npm info ok
```

**Comment by f1337** [comment]
Update: This may be a transient bug, or it may only occur when `h9 publish` is invoked via `npm run`. No such errors today when invoking `h9 publish` directly, via a newly-created h9 Docker image:

```
$ docker run -it --rm -v ~/.aws:/root/.aws -v "$PWD":/usr/src/app haiku9 h9 publish staging
Scanning S3 bucket.
Scanning local repo.
Syncing S3 bucket.
> 100%
Configuring S3 bucket for static serving.
Establishing DNS record for site.
Direct S3 Serving.  HTTP-Only.
Waiting for DNS records to synchronize.
$ 
```

**Comment by f1337** [comment]
Confirmed, I cannot reproduce this morning. Was likely an actual remote timeout. Oops.
