### ISSUE TITLE
Cannot find module '../src' when running h9 serve via Docker

### ISSUE THREAD

**Issue by robbwagoner** [pandastrike/haiku9#93]
I get this by following the README for running haiku9 via Docker.

```
$ docker run -it --rm -v "$PWD":/usr/src/app -p 1337:1337 h9 serve
Error: Cannot find module '../src'
  at Function.Module._resolveFilename (module.js:455:15)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/src/app/node_modules/haiku9/bin/h9-serve:4:3)
  at Object.<anonymous> (/usr/src/app/node_modules/haiku9/bin/h9-serve:10:4)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/usr/src/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/src/app/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/src/app/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/src/app/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/src/app/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

**Comment by robbwagoner** [comment]
If I change line 3 of `bin/h9-serve` to `require "../lib"`, the local server loads and web site renders in my browser.

**Comment by dyoder** [comment]
Woops. Nice catch.

**Comment by f1337** [comment]
That should not be happening if your project is using the latest h9. I just encountered this issue with pandastrike.com repo, and fixed by upgrading to h9-beta-15.

**Comment by f1337** [comment]
@robbwagoner In what context did you encounter that error?

**Comment by f1337** [comment]
Ah, I just realized I took a short-cut with the Dockerfile, and that is the root cause here. To fix:

* Dockerfile should install h9 globally in the image (right now it's relying on the h9 version in your project's package.json)
* Use absolute path /usr/src/app (or whatever is used for WORKDIR) instead of `../src` for app code path in h9 binary.
